/**
 * Zod schemas generated by Orval. Import via:
 *   import { getHealthResponse } from '@bookee/api-client/zod';
 *
 * DO NOT manually edit anything inside src/generated/ — regenerate by
 * running `bun run codegen` after the backend exports a new openapi.yaml.
 */

export * from './generated/health/health.zod';
